### ISSUE TITLE
7544 "Angestrengtest"

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#166]
http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2.2/gsa_391247.xml&page=1&view=print&section=391247.all#l7544

In the line synopsis it appears as if H and 2 II H.74 read
> Angeſtregteſt

(n omitted)

But the textual transcirpt of II H.74 reads 
> Angeſtrengteſt

(with the n)

**Comment by thvitt** [comment]
Combination of #165 and https://github.com/faustedition/faust-web/issues/283#issuecomment-323717499: 
2 H contains:
```xml
<l n="7544">Angeſtre<corr>n</corr>gteſt, nimmer müde,</l>
```
The grouping in the current variant generation uses the `<l>`'s text representation, i.e. 2 H  and 2 II H.74 _both_ resolve to `Angeſtrengteſt, nimmer müde` and thus are grouped. For rendering, however, `2 H` is chosen, and since `corr` should be ommitted, this renders as `Angeſtregteſt, nimmer müde`

**Comment by gerritbruening** [comment]
Ah, I should have guessed this, too!
