### ISSUE TITLE
Apparatus containing page breaks strangely spread in 5093

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#169]
See
http://beta.faustedition.net/documentViewer?faustUri=faust://xml/document/archival/dla_marbach/Cotta-Archiv_Goethe_23.xml&page=27&view=print#l5093

**Comment by thvitt** [comment]
Are you talking about the apparatus in [2 H](http://beta.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=32&view=text#l5093)? For some reason the add/del are `<div>`s, not `<span>`s in HTML. This is probably a consequence of the `<pb/>` being part of the substitution:

```xml
<l n="5093">Mancher <subst f:revType="soon">
      <del><pb n="30"/>holden</del>
      <add><pb n="32"/>heiteren</add>
   </subst> Blume Zier</l>
<l n="5094"><subst f:revType="soon">
      <del><pb n="30"/>Seidenfaden</del>
      <add><pb n="32"/>Seidenfäden</add>
   </subst>, Seidenflocken</l>
```

(So make pb inline in util.xsl/f:isInline?)

**Comment by gerritbruening** [comment]
Ah, the `pb`s.
Inline would be good, if this does not have negative consequences for the rendering of the page numbers at the margin.

**Comment by thvitt** [comment]
A problem with that is that it is no longer recognizable that the page number 30 is deleted and replaced with 32 (that's what you intend to say with that encoding, isn't it?):

![new rendering with floating pbs](https://user-images.githubusercontent.com/1906208/33945189-a08b06d6-e01e-11e7-8a0e-575ac4ea5063.png)

This could maybe resolved by making page numbers which are affected by apparatus non-floating, rendering them inside the apparatus like that:

![new rendering with non-floating inline pbs](https://user-images.githubusercontent.com/1906208/33945655-f525dd64-e01f-11e7-8a62-1324b1070654.png)

However, its inconsistent since page numbers usually are in the margins

**Comment by gerritbruening** [comment]
Great, thanks for this quick fix.
Only irritating I see is the "32" directly after "2 I H.6"
