### ISSUE TITLE
Whitespace lost in before_6479_a

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#396]
391098's

                        <stage n="before_6479_a">
                           <hi status="name">Helena</hi>. (<subst ge:stage="#posthumous">
                              <del>tritt auf</del>
                              <add>hervortre<del f:revType="instant">d</del>tend</add>
                           </subst>)</stage>

seems OK, but in faust.xml there is

                                <hi>Helena</hi><seg type="lem" xml:id="seg.before_6479_a.trittauf"
                                    >tritt auf</seg>.<note type="textcrit"

**Comment by gerritbruening** [comment]
Whitespace---always great fun!

**Comment by thvitt** [comment]
I absolutely hate it. It is probably OK in `without-app.xml`, but I need to normalize whitespace for the insert app phase since the apparatus contains normalized whitespace … maybe reduce whitespace normalization to whitespace condensation there, that should do the trick.

OTOH the normalization routine probably should be fixed. If possible.

**Comment by gerritbruening** [comment]
Second case:

                                <speaker n="before_8359_a"><hi><seg type="lem"
                                            xml:id="seg.before_8359_a.psyllen">Psyllen</seg></hi>und
