### ISSUE TITLE
deliver grundschicht stuff for local use

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#545]
@thvitt, could I run the grundschicht generation on my own device just like I can run `prepare-reading-text`? (what I still do).

**Comment by thvitt** [comment]
sure, the implementation is pretty straight-forward. This sequence of stylesheets produces the grundschicht of _without_ instant revisions:

https://github.com/faustedition/faust-gen-html/blob/e3223c18bea1e11d5956bab4388595eea515293c/generate-all.xpl#L124-L145

I believe you can feed the unprepared textual transcripts in here, it takes the prepared stuff (f:label, f:section etc) in the pipeline but IIRC the scripts don’t do anything with that. I think you could also replace the parameter input with `<p:input port="parameters"><p:empty/></p:input>` since the configuration isn’t required.

For the grundschicht with instant revisions, replace unemend-core.xsl with emend-core-only-instant.xsl:

https://github.com/faustedition/faust-gen-html/blob/e3223c18bea1e11d5956bab4388595eea515293c/generate-all.xpl#L146-L157

**Comment by gerritbruening** [comment]
Thank you.
My idea is to include local paths for any xml files I have.

**Comment by gerritbruening** [comment]
Ah, I forgot I can insert these paths within the transformation scenario.
