### ISSUE TITLE
Line synopsis for Land Strase, 1 H.5 links on wrong scene

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#620]
> wenn ich aus dem Variantenparadigma der Textdarstellung von H P 6 (die 
> jetzt I H 5 verzeichnet - das ist prima, ganz vielen DANK!) auf I H 5 
> klicke, lande ich dort irgendwo. Wäre es möglich, den Link so zu 
> setzen, dass man bei dem entsprechenden Vers (oder am Anfang der 
> Szene) in I H 5 landet?

When you are in [H P6](http://dev.faustedition.net/document?sigil=H_P6&page=1&view=print), open the line synopsis, and change to 1 H.5, you are  in the wrong scene:
http://dev.faustedition.net/document?sigil=1_H.5&page=35&view=print#lu_455

> weil die land strase auch auf S. 35 steht

**Comment by thvitt** [comment]
it’s a conceptual issue. 

Land Straſe begins on p.35 which also contains content from the previous scene. The link goes to `&page=35`, and the document viewer loads the scene associated with that page (which is the scene _before_ page 35).

A link to the _section_ alone wouldn’t work, either: (a) because we don’t find the page for the section since the map is page → section, and (b) because the links for longer scenes should have page precision so we don’t jump to the beginning of the scene.

So,
1. we should link to `&page=…&section=…` from the synopsis
2. the section ↔ page map should allow for several sections on one page

**Comment by thvitt** [comment]
#618
